[2025-10-06T08:25:52.516+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.visualize_inventory manual__2025-10-06T08:25:23.670492+00:00 [queued]>
[2025-10-06T08:25:52.632+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.visualize_inventory manual__2025-10-06T08:25:23.670492+00:00 [queued]>
[2025-10-06T08:25:52.633+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-06T08:25:52.733+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): visualize_inventory> on 2025-10-06 08:25:23.670492+00:00
[2025-10-06T08:25:52.792+0000] {standard_task_runner.py:60} INFO - Started process 638 to run task
[2025-10-06T08:25:53.058+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inventory_analytics_pipeline', 'visualize_inventory', 'manual__2025-10-06T08:25:23.670492+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/inventory_analytics_pipeline.py', '--cfg-path', '/tmp/tmpi9bpnb77']
[2025-10-06T08:25:53.458+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask visualize_inventory
[2025-10-06T08:25:53.710+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-06T08:25:53.831+0000] {task_command.py:423} INFO - Running <TaskInstance: inventory_analytics_pipeline.visualize_inventory manual__2025-10-06T08:25:23.670492+00:00 [running]> on host ea4788e59d79
[2025-10-06T08:25:53.997+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inventory_analytics_pipeline' AIRFLOW_CTX_TASK_ID='visualize_inventory' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T08:25:23.670492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T08:25:23.670492+00:00'
[2025-10-06T08:25:55.821+0000] {logging_mixin.py:188} INFO - âœ… Inventory plot saved: /opt/***/data/plots/inventory_plot_20251006_082554.png
[2025-10-06T08:25:55.823+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-06T08:25:55.853+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=inventory_analytics_pipeline, task_id=visualize_inventory, execution_date=20251006T082523, start_date=20251006T082552, end_date=20251006T082555
[2025-10-06T08:25:56.015+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-06T08:25:56.104+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
